/*
###############################################################
#  Generated by:      Cadence Innovus 20.13-s083_1
#  OS:                Linux x86_64(Host ID iron-502-28)
#  Generated on:      Tue Jun  7 22:21:12 2022
#  Design:            user_proj_example
#  Command:           saveNetlist -excludeLeafCell results/user_proj_example.vcs.v
###############################################################
*/
module user_proj_example_RegRst_0x9f365fdf6c8998a_0 (
	clk, 
	in_, 
	out, 
	reset);
   input [0:0] clk;
   input [1:0] in_;
   output [1:0] out;
   input [0:0] reset;

   // Internal wires
   wire n1;
   wire n2;

   sky130_fd_sc_hd__dfxtp_1 out_reg_1_ (.CLK(clk[0]),
	.D(n2),
	.Q(out[1]));
   sky130_fd_sc_hd__dfxtp_1 out_reg_0_ (.CLK(clk[0]),
	.D(n1),
	.Q(out[0]));
   sky130_fd_sc_hd__nor2b_1 U3 (.A(reset[0]),
	.B_N(in_[0]),
	.Y(n1));
   sky130_fd_sc_hd__nor2b_1 U4 (.A(reset[0]),
	.B_N(in_[1]),
	.Y(n2));
endmodule

module user_proj_example_GcdUnitCtrlRTL_0x29124399ca008c5e_0 (
	a_mux_sel, 
	a_reg_en, 
	b_mux_sel, 
	b_reg_en, 
	clk, 
	is_a_lt_b, 
	is_b_zero, 
	req_rdy, 
	req_val, 
	reset, 
	resp_rdy, 
	resp_val);
   output [1:0] a_mux_sel;
   output [0:0] a_reg_en;
   output [0:0] b_mux_sel;
   output [0:0] b_reg_en;
   input [0:0] clk;
   input [0:0] is_a_lt_b;
   input [0:0] is_b_zero;
   output [0:0] req_rdy;
   input [0:0] req_val;
   input [0:0] reset;
   input [0:0] resp_rdy;
   output [0:0] resp_val;

   // Internal wires
   wire FE_RN_1;
   wire n1;
   wire n2;
   wire n3;
   wire n4;
   wire [1:0] state_out;
   wire [1:0] next_state__0;

   assign req_rdy[0] = FE_RN_1 ;

   user_proj_example_RegRst_0x9f365fdf6c8998a_0 state (.clk(clk),
	.in_(next_state__0),
	.out(state_out),
	.reset(reset));
   sky130_fd_sc_hd__nor2_2 U3 (.A(state_out[1]),
	.B(state_out[0]),
	.Y(FE_RN_1));
   sky130_fd_sc_hd__clkinv_1 U5 (.A(state_out[1]),
	.Y(a_reg_en[0]));
   sky130_fd_sc_hd__clkinv_1 U6 (.A(state_out[0]),
	.Y(n3));
   sky130_fd_sc_hd__nand2_1 U7 (.A(is_a_lt_b[0]),
	.B(a_reg_en[0]),
	.Y(n4));
   sky130_fd_sc_hd__nor2_1 U8 (.A(n3),
	.B(n4),
	.Y(a_mux_sel[1]));
   sky130_fd_sc_hd__nor3_1 U9 (.A(state_out[1]),
	.B(is_a_lt_b[0]),
	.C(n3),
	.Y(a_mux_sel[0]));
   sky130_fd_sc_hd__a21oi_1 U10 (.A1(req_val[0]),
	.A2(a_reg_en[0]),
	.B1(state_out[0]),
	.Y(n1));
   sky130_fd_sc_hd__a21oi_1 U11 (.A1(is_b_zero[0]),
	.A2(a_mux_sel[0]),
	.B1(n1),
	.Y(next_state__0[0]));
   sky130_fd_sc_hd__nor2_1 U12 (.A(state_out[0]),
	.B(a_reg_en[0]),
	.Y(resp_val[0]));
   sky130_fd_sc_hd__nand2_1 U13 (.A(a_mux_sel[0]),
	.B(is_b_zero[0]),
	.Y(n2));
   sky130_fd_sc_hd__a22oi_1 U14 (.A1(n3),
	.A2(resp_rdy[0]),
	.B1(n2),
	.B2(a_reg_en[0]),
	.Y(next_state__0[1]));
   sky130_fd_sc_hd__nand2b_1 U15 (.A_N(FE_RN_1),
	.B(n4),
	.Y(b_reg_en[0]));
endmodule

module user_proj_example_SNPS_CLOCK_GATE_HIGH_RegEn_0x68db79c4ec1d6e5b_1_0 (
	EN, 
	TE, 
	ENCLK, 
	ENCLK_clone1, 
	CLK);
   input EN;
   input TE;
   output ENCLK;
   output ENCLK_clone1;
   input CLK;

   sky130_fd_sc_hd__sdlclkp_4 latch_clone_2 (.CLK(CLK),
	.GATE(EN),
	.GCLK(ENCLK_clone1),
	.SCE(TE));
   sky130_fd_sc_hd__sdlclkp_4 latch_clone (.CLK(CLK),
	.GATE(EN),
	.GCLK(ENCLK),
	.SCE(TE));
endmodule

module user_proj_example_RegEn_0x68db79c4ec1d6e5b_0 (
	clk, 
	en, 
	in_, 
	out, 
	reset);
   input [0:0] clk;
   input [0:0] en;
   input [15:0] in_;
   output [15:0] out;
   input [0:0] reset;

   // Internal wires
   wire CTS_2;
   wire CTS_1;
   wire net658;

   user_proj_example_SNPS_CLOCK_GATE_HIGH_RegEn_0x68db79c4ec1d6e5b_1_0 clk_gate_out_reg (.EN(en[0]),
	.TE(net658),
	.ENCLK(CTS_1),
	.ENCLK_clone1(CTS_2),
	.CLK(clk[0]));
   sky130_fd_sc_hd__dfxtp_1 out_reg_15_ (.CLK(CTS_2),
	.D(in_[15]),
	.Q(out[15]));
   sky130_fd_sc_hd__dfxtp_1 out_reg_14_ (.CLK(CTS_2),
	.D(in_[14]),
	.Q(out[14]));
   sky130_fd_sc_hd__dfxtp_1 out_reg_13_ (.CLK(CTS_2),
	.D(in_[13]),
	.Q(out[13]));
   sky130_fd_sc_hd__dfxtp_1 out_reg_12_ (.CLK(CTS_2),
	.D(in_[12]),
	.Q(out[12]));
   sky130_fd_sc_hd__dfxtp_1 out_reg_11_ (.CLK(CTS_2),
	.D(in_[11]),
	.Q(out[11]));
   sky130_fd_sc_hd__dfxtp_1 out_reg_10_ (.CLK(CTS_2),
	.D(in_[10]),
	.Q(out[10]));
   sky130_fd_sc_hd__dfxtp_1 out_reg_9_ (.CLK(CTS_1),
	.D(in_[9]),
	.Q(out[9]));
   sky130_fd_sc_hd__dfxtp_1 out_reg_8_ (.CLK(CTS_1),
	.D(in_[8]),
	.Q(out[8]));
   sky130_fd_sc_hd__dfxtp_1 out_reg_7_ (.CLK(CTS_1),
	.D(in_[7]),
	.Q(out[7]));
   sky130_fd_sc_hd__dfxtp_1 out_reg_6_ (.CLK(CTS_1),
	.D(in_[6]),
	.Q(out[6]));
   sky130_fd_sc_hd__dfxtp_1 out_reg_5_ (.CLK(CTS_1),
	.D(in_[5]),
	.Q(out[5]));
   sky130_fd_sc_hd__dfxtp_1 out_reg_4_ (.CLK(CTS_1),
	.D(in_[4]),
	.Q(out[4]));
   sky130_fd_sc_hd__dfxtp_1 out_reg_3_ (.CLK(CTS_1),
	.D(in_[3]),
	.Q(out[3]));
   sky130_fd_sc_hd__dfxtp_1 out_reg_2_ (.CLK(CTS_1),
	.D(in_[2]),
	.Q(out[2]));
   sky130_fd_sc_hd__dfxtp_1 out_reg_1_ (.CLK(CTS_1),
	.D(in_[1]),
	.Q(out[1]));
   sky130_fd_sc_hd__dfxtp_1 out_reg_0_ (.CLK(CTS_1),
	.D(in_[0]),
	.Q(out[0]));
   sky130_fd_sc_hd__conb_1 U2 (.LO(net658));
endmodule

module user_proj_example_LtComparator_0x422b1f52edd46a85_0 (
	clk, 
	in0, 
	in1, 
	out, 
	reset);
   input [0:0] clk;
   input [15:0] in0;
   input [15:0] in1;
   output [0:0] out;
   input [0:0] reset;

   // Internal wires
   wire n1;
   wire n2;
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n7;
   wire n8;
   wire n9;
   wire n10;
   wire n11;
   wire n12;
   wire n13;
   wire n14;
   wire n15;
   wire n16;
   wire n17;
   wire n18;
   wire n19;
   wire n20;
   wire n21;
   wire n22;
   wire n23;
   wire n24;
   wire n25;
   wire n26;
   wire n27;
   wire n28;
   wire n29;
   wire n30;
   wire n31;
   wire n32;
   wire n33;
   wire n34;
   wire n35;
   wire n36;
   wire n37;
   wire n38;
   wire n39;
   wire n40;
   wire n41;
   wire n42;
   wire n43;
   wire n44;
   wire n45;

   sky130_fd_sc_hd__clkinv_1 U1 (.A(in1[15]),
	.Y(n45));
   sky130_fd_sc_hd__nor2_1 U2 (.A(in0[15]),
	.B(n45),
	.Y(n43));
   sky130_fd_sc_hd__clkinv_1 U3 (.A(in0[13]),
	.Y(n36));
   sky130_fd_sc_hd__clkinv_1 U4 (.A(in1[12]),
	.Y(n34));
   sky130_fd_sc_hd__clkinv_1 U5 (.A(in1[11]),
	.Y(n1));
   sky130_fd_sc_hd__a22o_1 U6 (.A1(n1),
	.A2(in0[11]),
	.B1(n34),
	.B2(in0[12]),
	.X(n33));
   sky130_fd_sc_hd__nor2_1 U7 (.A(in0[11]),
	.B(n1),
	.Y(n31));
   sky130_fd_sc_hd__clkinv_1 U8 (.A(in0[8]),
	.Y(n22));
   sky130_fd_sc_hd__clkinv_1 U9 (.A(in1[7]),
	.Y(n19));
   sky130_fd_sc_hd__clkinv_1 U10 (.A(in1[5]),
	.Y(n14));
   sky130_fd_sc_hd__clkinv_1 U11 (.A(in0[3]),
	.Y(n7));
   sky130_fd_sc_hd__clkinv_1 U12 (.A(in1[1]),
	.Y(n3));
   sky130_fd_sc_hd__nand2b_1 U13 (.A_N(in0[0]),
	.B(in1[0]),
	.Y(n2));
   sky130_fd_sc_hd__a222oi_1 U14 (.A1(in0[1]),
	.A2(n3),
	.B1(in0[1]),
	.B2(n2),
	.C1(n3),
	.C2(n2),
	.Y(n5));
   sky130_fd_sc_hd__clkinv_1 U15 (.A(in0[2]),
	.Y(n4));
   sky130_fd_sc_hd__maj3_1 U16 (.A(in1[2]),
	.B(n5),
	.C(n4),
	.X(n6));
   sky130_fd_sc_hd__maj3_1 U17 (.A(in1[3]),
	.B(n7),
	.C(n6),
	.X(n11));
   sky130_fd_sc_hd__nand2_1 U18 (.A(in0[5]),
	.B(n14),
	.Y(n10));
   sky130_fd_sc_hd__nand2_1 U19 (.A(in1[4]),
	.B(n11),
	.Y(n8));
   sky130_fd_sc_hd__nand2_1 U20 (.A(in0[4]),
	.B(n8),
	.Y(n9));
   sky130_fd_sc_hd__o211ai_1 U21 (.A1(in1[4]),
	.A2(n11),
	.B1(n10),
	.C1(n9),
	.Y(n13));
   sky130_fd_sc_hd__nor2_1 U22 (.A(n19),
	.B(in0[7]),
	.Y(n15));
   sky130_fd_sc_hd__clkinv_1 U23 (.A(n15),
	.Y(n12));
   sky130_fd_sc_hd__o211ai_1 U24 (.A1(in0[5]),
	.A2(n14),
	.B1(n13),
	.C1(n12),
	.Y(n17));
   sky130_fd_sc_hd__o21ai_1 U25 (.A1(in1[6]),
	.A2(n15),
	.B1(n17),
	.Y(n16));
   sky130_fd_sc_hd__o2bb2ai_1 U26 (.A1_N(in0[6]),
	.A2_N(n16),
	.B1(n17),
	.B2(in1[6]),
	.Y(n18));
   sky130_fd_sc_hd__a21oi_1 U27 (.A1(in0[7]),
	.A2(n19),
	.B1(n18),
	.Y(n21));
   sky130_fd_sc_hd__clkinv_1 U28 (.A(in1[10]),
	.Y(n26));
   sky130_fd_sc_hd__nor2_1 U29 (.A(in0[10]),
	.B(n26),
	.Y(n20));
   sky130_fd_sc_hd__a211oi_1 U30 (.A1(in1[8]),
	.A2(n22),
	.B1(n21),
	.C1(n20),
	.Y(n29));
   sky130_fd_sc_hd__clkinv_1 U31 (.A(in0[9]),
	.Y(n23));
   sky130_fd_sc_hd__nand2_1 U32 (.A(in1[9]),
	.B(n23),
	.Y(n28));
   sky130_fd_sc_hd__nand2_1 U33 (.A(in0[8]),
	.B(n28),
	.Y(n24));
   sky130_fd_sc_hd__o22ai_1 U34 (.A1(in1[8]),
	.A2(n24),
	.B1(in1[9]),
	.B2(n23),
	.Y(n25));
   sky130_fd_sc_hd__maj3_1 U35 (.A(in0[10]),
	.B(n26),
	.C(n25),
	.X(n27));
   sky130_fd_sc_hd__a21oi_1 U36 (.A1(n29),
	.A2(n28),
	.B1(n27),
	.Y(n30));
   sky130_fd_sc_hd__nor2_1 U37 (.A(n31),
	.B(n30),
	.Y(n32));
   sky130_fd_sc_hd__o22ai_1 U38 (.A1(in0[12]),
	.A2(n34),
	.B1(n33),
	.B2(n32),
	.Y(n35));
   sky130_fd_sc_hd__a21oi_1 U39 (.A1(in1[13]),
	.A2(n36),
	.B1(n35),
	.Y(n41));
   sky130_fd_sc_hd__clkinv_1 U40 (.A(in0[14]),
	.Y(n37));
   sky130_fd_sc_hd__nand2_1 U41 (.A(in1[14]),
	.B(n37),
	.Y(n40));
   sky130_fd_sc_hd__nand2_1 U42 (.A(in0[13]),
	.B(n40),
	.Y(n38));
   sky130_fd_sc_hd__o22ai_1 U43 (.A1(in1[13]),
	.A2(n38),
	.B1(in1[14]),
	.B2(n37),
	.Y(n39));
   sky130_fd_sc_hd__a21oi_1 U44 (.A1(n41),
	.A2(n40),
	.B1(n39),
	.Y(n42));
   sky130_fd_sc_hd__nor2_1 U45 (.A(n43),
	.B(n42),
	.Y(n44));
   sky130_fd_sc_hd__a21oi_1 U46 (.A1(in0[15]),
	.A2(n45),
	.B1(n44),
	.Y(out[0]));
endmodule

module user_proj_example_ZeroComparator_0x422b1f52edd46a85_0 (
	clk, 
	in_, 
	out, 
	reset);
   input [0:0] clk;
   input [15:0] in_;
   output [0:0] out;
   input [0:0] reset;

   // Internal wires
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   sky130_fd_sc_hd__nor4_1 U1 (.A(in_[12]),
	.B(in_[13]),
	.C(in_[14]),
	.D(in_[15]),
	.Y(n4));
   sky130_fd_sc_hd__nor4_1 U2 (.A(in_[8]),
	.B(in_[9]),
	.C(in_[10]),
	.D(in_[11]),
	.Y(n3));
   sky130_fd_sc_hd__nor4_1 U3 (.A(in_[4]),
	.B(in_[5]),
	.C(in_[6]),
	.D(in_[7]),
	.Y(n2));
   sky130_fd_sc_hd__nor4_1 U4 (.A(in_[0]),
	.B(in_[1]),
	.C(in_[2]),
	.D(in_[3]),
	.Y(n1));
   sky130_fd_sc_hd__and4_1 U5 (.A(n4),
	.B(n3),
	.C(n2),
	.D(n1),
	.X(out[0]));
endmodule

module user_proj_example_Mux_0x683fa1a418b072c9_0 (
	clk, 
	in__000, 
	in__001, 
	in__002, 
	out, 
	reset, 
	sel);
   input [0:0] clk;
   input [15:0] in__000;
   input [15:0] in__001;
   input [15:0] in__002;
   output [15:0] out;
   input [0:0] reset;
   input [1:0] sel;

   // Internal wires
   wire n1;
   wire n2;
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n7;
   wire n8;
   wire n9;
   wire n10;
   wire n11;
   wire n12;
   wire n13;
   wire n14;
   wire n15;
   wire n16;
   wire n17;
   wire n18;

   sky130_fd_sc_hd__a222oi_1 U3 (.A1(sel[1]),
	.A2(in__002[14]),
	.B1(n17),
	.B2(in__001[14]),
	.C1(n16),
	.C2(in__000[14]),
	.Y(n1));
   sky130_fd_sc_hd__clkinv_1 U4 (.A(n1),
	.Y(out[14]));
   sky130_fd_sc_hd__a222oi_1 U5 (.A1(sel[1]),
	.A2(in__002[15]),
	.B1(n17),
	.B2(in__001[15]),
	.C1(n16),
	.C2(in__000[15]),
	.Y(n2));
   sky130_fd_sc_hd__clkinv_1 U6 (.A(n2),
	.Y(out[15]));
   sky130_fd_sc_hd__a222oi_1 U7 (.A1(sel[1]),
	.A2(in__002[3]),
	.B1(n17),
	.B2(in__001[3]),
	.C1(n16),
	.C2(in__000[3]),
	.Y(n3));
   sky130_fd_sc_hd__clkinv_1 U8 (.A(n3),
	.Y(out[3]));
   sky130_fd_sc_hd__a222oi_1 U9 (.A1(sel[1]),
	.A2(in__002[9]),
	.B1(n17),
	.B2(in__001[9]),
	.C1(n16),
	.C2(in__000[9]),
	.Y(n4));
   sky130_fd_sc_hd__clkinv_1 U10 (.A(n4),
	.Y(out[9]));
   sky130_fd_sc_hd__a222oi_1 U11 (.A1(sel[1]),
	.A2(in__002[1]),
	.B1(n17),
	.B2(in__001[1]),
	.C1(n16),
	.C2(in__000[1]),
	.Y(n5));
   sky130_fd_sc_hd__clkinv_1 U12 (.A(n5),
	.Y(out[1]));
   sky130_fd_sc_hd__a222oi_1 U13 (.A1(sel[1]),
	.A2(in__002[0]),
	.B1(n17),
	.B2(in__001[0]),
	.C1(n16),
	.C2(in__000[0]),
	.Y(n6));
   sky130_fd_sc_hd__clkinv_1 U14 (.A(n6),
	.Y(out[0]));
   sky130_fd_sc_hd__a222oi_1 U15 (.A1(sel[1]),
	.A2(in__002[5]),
	.B1(n17),
	.B2(in__001[5]),
	.C1(n16),
	.C2(in__000[5]),
	.Y(n7));
   sky130_fd_sc_hd__clkinv_1 U16 (.A(n7),
	.Y(out[5]));
   sky130_fd_sc_hd__a222oi_1 U17 (.A1(sel[1]),
	.A2(in__002[2]),
	.B1(n17),
	.B2(in__001[2]),
	.C1(n16),
	.C2(in__000[2]),
	.Y(n8));
   sky130_fd_sc_hd__clkinv_1 U18 (.A(n8),
	.Y(out[2]));
   sky130_fd_sc_hd__a222oi_1 U19 (.A1(sel[1]),
	.A2(in__002[7]),
	.B1(n17),
	.B2(in__001[7]),
	.C1(n16),
	.C2(in__000[7]),
	.Y(n9));
   sky130_fd_sc_hd__clkinv_1 U20 (.A(n9),
	.Y(out[7]));
   sky130_fd_sc_hd__a222oi_1 U21 (.A1(sel[1]),
	.A2(in__002[6]),
	.B1(n17),
	.B2(in__001[6]),
	.C1(n16),
	.C2(in__000[6]),
	.Y(n10));
   sky130_fd_sc_hd__clkinv_1 U22 (.A(n10),
	.Y(out[6]));
   sky130_fd_sc_hd__a222oi_1 U23 (.A1(sel[1]),
	.A2(in__002[11]),
	.B1(n17),
	.B2(in__001[11]),
	.C1(n16),
	.C2(in__000[11]),
	.Y(n11));
   sky130_fd_sc_hd__clkinv_1 U24 (.A(n11),
	.Y(out[11]));
   sky130_fd_sc_hd__a222oi_1 U25 (.A1(sel[1]),
	.A2(in__002[8]),
	.B1(n17),
	.B2(in__001[8]),
	.C1(n16),
	.C2(in__000[8]),
	.Y(n12));
   sky130_fd_sc_hd__clkinv_1 U26 (.A(n12),
	.Y(out[8]));
   sky130_fd_sc_hd__a222oi_1 U27 (.A1(sel[1]),
	.A2(in__002[4]),
	.B1(n17),
	.B2(in__001[4]),
	.C1(n16),
	.C2(in__000[4]),
	.Y(n13));
   sky130_fd_sc_hd__clkinv_1 U28 (.A(n13),
	.Y(out[4]));
   sky130_fd_sc_hd__a222oi_1 U29 (.A1(sel[1]),
	.A2(in__002[10]),
	.B1(n17),
	.B2(in__001[10]),
	.C1(n16),
	.C2(in__000[10]),
	.Y(n14));
   sky130_fd_sc_hd__clkinv_1 U30 (.A(n14),
	.Y(out[10]));
   sky130_fd_sc_hd__a222oi_1 U31 (.A1(sel[1]),
	.A2(in__002[12]),
	.B1(n17),
	.B2(in__001[12]),
	.C1(n16),
	.C2(in__000[12]),
	.Y(n15));
   sky130_fd_sc_hd__clkinv_1 U32 (.A(n15),
	.Y(out[12]));
   sky130_fd_sc_hd__a222oi_1 U33 (.A1(sel[1]),
	.A2(in__002[13]),
	.B1(n17),
	.B2(in__001[13]),
	.C1(n16),
	.C2(in__000[13]),
	.Y(n18));
   sky130_fd_sc_hd__clkinv_1 U34 (.A(n18),
	.Y(out[13]));
   sky130_fd_sc_hd__nor2b_1 U1 (.A(sel[1]),
	.B_N(sel[0]),
	.Y(n17));
   sky130_fd_sc_hd__nor2_1 U2 (.A(sel[1]),
	.B(sel[0]),
	.Y(n16));
endmodule

module user_proj_example_Mux_0xdd6473406d1a99a_0 (
	clk, 
	in__000, 
	in__001, 
	out, 
	reset, 
	sel);
   input [0:0] clk;
   input [15:0] in__000;
   input [15:0] in__001;
   output [15:0] out;
   input [0:0] reset;
   input [0:0] sel;

   // Internal wires
   wire n2;

   sky130_fd_sc_hd__a22o_1 U2 (.A1(sel[0]),
	.A2(in__001[0]),
	.B1(n2),
	.B2(in__000[0]),
	.X(out[0]));
   sky130_fd_sc_hd__a22o_1 U3 (.A1(sel[0]),
	.A2(in__001[1]),
	.B1(n2),
	.B2(in__000[1]),
	.X(out[1]));
   sky130_fd_sc_hd__a22o_1 U4 (.A1(sel[0]),
	.A2(in__001[2]),
	.B1(n2),
	.B2(in__000[2]),
	.X(out[2]));
   sky130_fd_sc_hd__a22o_1 U5 (.A1(sel[0]),
	.A2(in__001[3]),
	.B1(n2),
	.B2(in__000[3]),
	.X(out[3]));
   sky130_fd_sc_hd__a22o_1 U6 (.A1(sel[0]),
	.A2(in__001[4]),
	.B1(n2),
	.B2(in__000[4]),
	.X(out[4]));
   sky130_fd_sc_hd__a22o_1 U7 (.A1(sel[0]),
	.A2(in__001[5]),
	.B1(n2),
	.B2(in__000[5]),
	.X(out[5]));
   sky130_fd_sc_hd__a22o_1 U8 (.A1(sel[0]),
	.A2(in__001[6]),
	.B1(n2),
	.B2(in__000[6]),
	.X(out[6]));
   sky130_fd_sc_hd__a22o_1 U9 (.A1(sel[0]),
	.A2(in__001[7]),
	.B1(n2),
	.B2(in__000[7]),
	.X(out[7]));
   sky130_fd_sc_hd__a22o_1 U10 (.A1(sel[0]),
	.A2(in__001[8]),
	.B1(n2),
	.B2(in__000[8]),
	.X(out[8]));
   sky130_fd_sc_hd__a22o_1 U11 (.A1(sel[0]),
	.A2(in__001[9]),
	.B1(n2),
	.B2(in__000[9]),
	.X(out[9]));
   sky130_fd_sc_hd__a22o_1 U12 (.A1(sel[0]),
	.A2(in__001[10]),
	.B1(n2),
	.B2(in__000[10]),
	.X(out[10]));
   sky130_fd_sc_hd__a22o_1 U13 (.A1(sel[0]),
	.A2(in__001[11]),
	.B1(n2),
	.B2(in__000[11]),
	.X(out[11]));
   sky130_fd_sc_hd__a22o_1 U14 (.A1(sel[0]),
	.A2(in__001[12]),
	.B1(n2),
	.B2(in__000[12]),
	.X(out[12]));
   sky130_fd_sc_hd__a22o_1 U15 (.A1(sel[0]),
	.A2(in__001[13]),
	.B1(n2),
	.B2(in__000[13]),
	.X(out[13]));
   sky130_fd_sc_hd__a22o_1 U16 (.A1(sel[0]),
	.A2(in__001[14]),
	.B1(n2),
	.B2(in__000[14]),
	.X(out[14]));
   sky130_fd_sc_hd__a22o_1 U17 (.A1(sel[0]),
	.A2(in__001[15]),
	.B1(n2),
	.B2(in__000[15]),
	.X(out[15]));
   sky130_fd_sc_hd__clkinv_1 U1 (.A(sel[0]),
	.Y(n2));
endmodule

module user_proj_example_Subtractor_0x422b1f52edd46a85_DW01_sub_J1_0_0 (
	A, 
	B, 
	CI, 
	DIFF, 
	CO);
   input [15:0] A;
   input [15:0] B;
   input CI;
   output [15:0] DIFF;
   output CO;

   // Internal wires
   wire n87;
   wire n88;
   wire n89;
   wire n90;
   wire n91;
   wire n92;
   wire n93;
   wire n94;
   wire n95;
   wire n96;
   wire n97;
   wire n98;
   wire n99;
   wire n100;
   wire n101;
   wire n102;
   wire n103;
   wire n104;
   wire n105;
   wire n106;
   wire n107;
   wire n108;
   wire n109;
   wire n110;
   wire n111;
   wire n112;
   wire n113;
   wire n114;
   wire n115;
   wire n116;

   sky130_fd_sc_hd__nand2b_1 U52 (.A_N(A[0]),
	.B(B[0]),
	.Y(n89));
   sky130_fd_sc_hd__xor2_1 U53 (.A(A[15]),
	.B(n87),
	.X(n88));
   sky130_fd_sc_hd__xnor2_1 U54 (.A(B[15]),
	.B(n88),
	.Y(DIFF[15]));
   sky130_fd_sc_hd__xor2_1 U55 (.A(A[0]),
	.B(B[0]),
	.X(DIFF[0]));
   sky130_fd_sc_hd__fa_2 U56 (.A(A[1]),
	.B(n90),
	.CIN(n89),
	.COUT(n91),
	.SUM(DIFF[1]));
   sky130_fd_sc_hd__fa_2 U57 (.A(A[2]),
	.B(n92),
	.CIN(n91),
	.COUT(n93),
	.SUM(DIFF[2]));
   sky130_fd_sc_hd__fa_2 U58 (.A(A[3]),
	.B(n94),
	.CIN(n93),
	.COUT(n95),
	.SUM(DIFF[3]));
   sky130_fd_sc_hd__fa_2 U59 (.A(A[4]),
	.B(n96),
	.CIN(n95),
	.COUT(n97),
	.SUM(DIFF[4]));
   sky130_fd_sc_hd__fa_2 U60 (.A(A[5]),
	.B(n98),
	.CIN(n97),
	.COUT(n99),
	.SUM(DIFF[5]));
   sky130_fd_sc_hd__fa_2 U61 (.A(A[6]),
	.B(n100),
	.CIN(n99),
	.COUT(n101),
	.SUM(DIFF[6]));
   sky130_fd_sc_hd__fa_2 U62 (.A(A[7]),
	.B(n102),
	.CIN(n101),
	.COUT(n103),
	.SUM(DIFF[7]));
   sky130_fd_sc_hd__fa_2 U63 (.A(A[8]),
	.B(n104),
	.CIN(n103),
	.COUT(n105),
	.SUM(DIFF[8]));
   sky130_fd_sc_hd__fa_2 U64 (.A(A[9]),
	.B(n106),
	.CIN(n105),
	.COUT(n107),
	.SUM(DIFF[9]));
   sky130_fd_sc_hd__fa_2 U65 (.A(A[10]),
	.B(n108),
	.CIN(n107),
	.COUT(n109),
	.SUM(DIFF[10]));
   sky130_fd_sc_hd__fa_2 U66 (.A(A[11]),
	.B(n110),
	.CIN(n109),
	.COUT(n111),
	.SUM(DIFF[11]));
   sky130_fd_sc_hd__fa_2 U67 (.A(A[12]),
	.B(n112),
	.CIN(n111),
	.COUT(n113),
	.SUM(DIFF[12]));
   sky130_fd_sc_hd__fa_2 U68 (.A(A[13]),
	.B(n114),
	.CIN(n113),
	.COUT(n115),
	.SUM(DIFF[13]));
   sky130_fd_sc_hd__fa_2 U69 (.A(A[14]),
	.B(n116),
	.CIN(n115),
	.COUT(n87),
	.SUM(DIFF[14]));
   sky130_fd_sc_hd__clkinv_1 U39 (.A(B[13]),
	.Y(n114));
   sky130_fd_sc_hd__clkinv_1 U38 (.A(B[14]),
	.Y(n116));
   sky130_fd_sc_hd__clkinv_1 U40 (.A(B[12]),
	.Y(n112));
   sky130_fd_sc_hd__clkinv_1 U43 (.A(B[9]),
	.Y(n106));
   sky130_fd_sc_hd__clkinv_1 U42 (.A(B[10]),
	.Y(n108));
   sky130_fd_sc_hd__clkinv_1 U41 (.A(B[11]),
	.Y(n110));
   sky130_fd_sc_hd__clkinv_1 U44 (.A(B[8]),
	.Y(n104));
   sky130_fd_sc_hd__clkinv_1 U45 (.A(B[7]),
	.Y(n102));
   sky130_fd_sc_hd__clkinv_1 U48 (.A(B[4]),
	.Y(n96));
   sky130_fd_sc_hd__clkinv_1 U47 (.A(B[5]),
	.Y(n98));
   sky130_fd_sc_hd__clkinv_1 U46 (.A(B[6]),
	.Y(n100));
   sky130_fd_sc_hd__clkinv_1 U51 (.A(B[1]),
	.Y(n90));
   sky130_fd_sc_hd__clkinv_1 U50 (.A(B[2]),
	.Y(n92));
   sky130_fd_sc_hd__clkinv_1 U49 (.A(B[3]),
	.Y(n94));
endmodule

module user_proj_example_Subtractor_0x422b1f52edd46a85_0 (
	clk, 
	in0, 
	in1, 
	out, 
	reset);
   input [0:0] clk;
   input [15:0] in0;
   input [15:0] in1;
   output [15:0] out;
   input [0:0] reset;

   // Internal wires
   wire n1;

   user_proj_example_Subtractor_0x422b1f52edd46a85_DW01_sub_J1_0_0 sub_x_1 (.A(in0),
	.B(in1),
	.CI(n1),
	.DIFF(out));
endmodule

module user_proj_example_SNPS_CLOCK_GATE_HIGH_RegEn_0x68db79c4ec1d6e5b_0_0 (
	EN, 
	TE, 
	ENCLK, 
	ENCLK_clone1, 
	CLK);
   input EN;
   input TE;
   output ENCLK;
   output ENCLK_clone1;
   input CLK;

   sky130_fd_sc_hd__sdlclkp_4 latch_clone_2 (.CLK(CLK),
	.GATE(EN),
	.GCLK(ENCLK_clone1),
	.SCE(TE));
   sky130_fd_sc_hd__sdlclkp_4 latch_clone (.CLK(CLK),
	.GATE(EN),
	.GCLK(ENCLK),
	.SCE(TE));
endmodule

module user_proj_example_RegEn_0x68db79c4ec1d6e5b_1 (
	clk, 
	en, 
	in_, 
	out, 
	reset);
   input [0:0] clk;
   input [0:0] en;
   input [15:0] in_;
   output [15:0] out;
   input [0:0] reset;

   // Internal wires
   wire CTS_2;
   wire CTS_1;
   wire net640;

   user_proj_example_SNPS_CLOCK_GATE_HIGH_RegEn_0x68db79c4ec1d6e5b_0_0 clk_gate_out_reg (.EN(en[0]),
	.TE(net640),
	.ENCLK(CTS_1),
	.ENCLK_clone1(CTS_2),
	.CLK(clk[0]));
   sky130_fd_sc_hd__dfxtp_1 out_reg_15_ (.CLK(CTS_2),
	.D(in_[15]),
	.Q(out[15]));
   sky130_fd_sc_hd__dfxtp_1 out_reg_14_ (.CLK(CTS_2),
	.D(in_[14]),
	.Q(out[14]));
   sky130_fd_sc_hd__dfxtp_1 out_reg_13_ (.CLK(CTS_2),
	.D(in_[13]),
	.Q(out[13]));
   sky130_fd_sc_hd__dfxtp_1 out_reg_12_ (.CLK(CTS_2),
	.D(in_[12]),
	.Q(out[12]));
   sky130_fd_sc_hd__dfxtp_1 out_reg_11_ (.CLK(CTS_2),
	.D(in_[11]),
	.Q(out[11]));
   sky130_fd_sc_hd__dfxtp_1 out_reg_10_ (.CLK(CTS_2),
	.D(in_[10]),
	.Q(out[10]));
   sky130_fd_sc_hd__dfxtp_1 out_reg_9_ (.CLK(CTS_2),
	.D(in_[9]),
	.Q(out[9]));
   sky130_fd_sc_hd__dfxtp_1 out_reg_8_ (.CLK(CTS_2),
	.D(in_[8]),
	.Q(out[8]));
   sky130_fd_sc_hd__dfxtp_1 out_reg_7_ (.CLK(CTS_1),
	.D(in_[7]),
	.Q(out[7]));
   sky130_fd_sc_hd__dfxtp_1 out_reg_6_ (.CLK(CTS_1),
	.D(in_[6]),
	.Q(out[6]));
   sky130_fd_sc_hd__dfxtp_1 out_reg_5_ (.CLK(CTS_1),
	.D(in_[5]),
	.Q(out[5]));
   sky130_fd_sc_hd__dfxtp_1 out_reg_4_ (.CLK(CTS_1),
	.D(in_[4]),
	.Q(out[4]));
   sky130_fd_sc_hd__dfxtp_1 out_reg_3_ (.CLK(CTS_1),
	.D(in_[3]),
	.Q(out[3]));
   sky130_fd_sc_hd__dfxtp_1 out_reg_2_ (.CLK(CTS_1),
	.D(in_[2]),
	.Q(out[2]));
   sky130_fd_sc_hd__dfxtp_1 out_reg_1_ (.CLK(CTS_1),
	.D(in_[1]),
	.Q(out[1]));
   sky130_fd_sc_hd__dfxtp_1 out_reg_0_ (.CLK(CTS_1),
	.D(in_[0]),
	.Q(out[0]));
   sky130_fd_sc_hd__conb_1 U2 (.LO(net640));
endmodule

module user_proj_example_GcdUnitDpathRTL_0x29124399ca008c5e_0 (
	a_mux_sel, 
	a_reg_en, 
	b_mux_sel, 
	b_reg_en, 
	clk, 
	is_a_lt_b, 
	is_b_zero, 
	req_msg_a, 
	req_msg_b, 
	reset, 
	resp_msg);
   input [1:0] a_mux_sel;
   input [0:0] a_reg_en;
   input [0:0] b_mux_sel;
   input [0:0] b_reg_en;
   input [0:0] clk;
   output [0:0] is_a_lt_b;
   output [0:0] is_b_zero;
   input [15:0] req_msg_a;
   input [15:0] req_msg_b;
   input [0:0] reset;
   output [15:0] resp_msg;

   // Internal wires
   wire n1;
   wire n2;
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n7;
   wire n8;
   wire n9;
   wire n10;
   wire n11;
   wire n12;
   wire [15:0] a_reg_out;
   wire [15:0] a_mux_out;
   wire [15:0] b_mux_out;
   wire [15:0] b_reg_out;

   user_proj_example_RegEn_0x68db79c4ec1d6e5b_0 a_reg (.clk(clk),
	.en(a_reg_en),
	.in_(a_mux_out),
	.out(a_reg_out),
	.reset(n1));
   user_proj_example_LtComparator_0x422b1f52edd46a85_0 a_lt_b (.clk(n2),
	.in0(a_reg_out),
	.in1(b_reg_out),
	.out(is_a_lt_b),
	.reset(n3));
   user_proj_example_ZeroComparator_0x422b1f52edd46a85_0 b_zero (.clk(n4),
	.in_(b_reg_out),
	.out(is_b_zero),
	.reset(n5));
   user_proj_example_Mux_0x683fa1a418b072c9_0 a_mux (.clk(n6),
	.in__000(req_msg_a),
	.in__001(resp_msg),
	.in__002(b_reg_out),
	.out(a_mux_out),
	.reset(n7),
	.sel(a_mux_sel));
   user_proj_example_Mux_0xdd6473406d1a99a_0 b_mux (.clk(n8),
	.in__000(a_reg_out),
	.in__001(req_msg_b),
	.out(b_mux_out),
	.reset(n9),
	.sel(b_mux_sel));
   user_proj_example_Subtractor_0x422b1f52edd46a85_0 sub (.clk(n10),
	.in0(a_reg_out),
	.in1(b_reg_out),
	.out(resp_msg),
	.reset(n11));
   user_proj_example_RegEn_0x68db79c4ec1d6e5b_1 b_reg (.clk(clk),
	.en(b_reg_en),
	.in_(b_mux_out),
	.out(b_reg_out),
	.reset(n12));
endmodule

module user_proj_example_GcdUnit_0 (
	clk, 
	req_msg, 
	req_rdy, 
	req_val, 
	reset, 
	resp_msg, 
	resp_rdy, 
	resp_val, 
	clk_clone1);
   input [0:0] clk;
   input [31:0] req_msg;
   output [0:0] req_rdy;
   input [0:0] req_val;
   input [0:0] reset;
   output [15:0] resp_msg;
   input [0:0] resp_rdy;
   output [0:0] resp_val;
   input clk_clone1;

   // Internal wires
   wire ctrl_b_mux_sel_0_;
   wire ctrl_b_reg_en_0_;
   wire ctrl_a_reg_en_0_;
   wire dpath_is_b_zero_0_;
   wire dpath_is_a_lt_b_0_;
   wire n1;
   wire [1:0] ctrl_a_mux_sel;

   user_proj_example_GcdUnitCtrlRTL_0x29124399ca008c5e_0 ctrl (.a_mux_sel(ctrl_a_mux_sel),
	.a_reg_en(ctrl_a_reg_en_0_),
	.b_mux_sel(ctrl_b_mux_sel_0_),
	.b_reg_en(ctrl_b_reg_en_0_),
	.clk(clk),
	.is_a_lt_b(dpath_is_a_lt_b_0_),
	.is_b_zero(dpath_is_b_zero_0_),
	.req_rdy(req_rdy),
	.req_val(req_val),
	.reset(reset),
	.resp_rdy(resp_rdy),
	.resp_val(resp_val));
   user_proj_example_GcdUnitDpathRTL_0x29124399ca008c5e_0 dpath (.a_mux_sel(ctrl_a_mux_sel),
	.a_reg_en(ctrl_a_reg_en_0_),
	.b_mux_sel(req_rdy),
	.b_reg_en(ctrl_b_reg_en_0_),
	.clk(clk_clone1),
	.is_a_lt_b(dpath_is_a_lt_b_0_),
	.is_b_zero(dpath_is_b_zero_0_),
	.req_msg_a({ req_msg[31],
		req_msg[30],
		req_msg[29],
		req_msg[28],
		req_msg[27],
		req_msg[26],
		req_msg[25],
		req_msg[24],
		req_msg[23],
		req_msg[22],
		req_msg[21],
		req_msg[20],
		req_msg[19],
		req_msg[18],
		req_msg[17],
		req_msg[16] }),
	.req_msg_b({ req_msg[15],
		req_msg[14],
		req_msg[13],
		req_msg[12],
		req_msg[11],
		req_msg[10],
		req_msg[9],
		req_msg[8],
		req_msg[7],
		req_msg[6],
		req_msg[5],
		req_msg[4],
		req_msg[3],
		req_msg[2],
		req_msg[1],
		req_msg[0] }),
	.reset(n1),
	.resp_msg(resp_msg));
endmodule

module user_proj_example (
	wb_clk_i, 
	wb_rst_i, 
	wbs_stb_i, 
	wbs_cyc_i, 
	wbs_we_i, 
	wbs_sel_i, 
	wbs_dat_i, 
	wbs_adr_i, 
	wbs_ack_o, 
	wbs_dat_o, 
	la_data_in, 
	la_data_out, 
	la_oenb, 
	io_in, 
	io_out, 
	io_oeb, 
	analog_io, 
	user_clock2, 
	user_irq);
   input wb_clk_i;
   input wb_rst_i;
   input wbs_stb_i;
   input wbs_cyc_i;
   input wbs_we_i;
   input [3:0] wbs_sel_i;
   input [31:0] wbs_dat_i;
   input [31:0] wbs_adr_i;
   output wbs_ack_o;
   output [31:0] wbs_dat_o;
   input [127:0] la_data_in;
   output [127:0] la_data_out;
   input [127:0] la_oenb;
   input [37:0] io_in;
   output [37:0] io_out;
   output [37:0] io_oeb;
   inout [28:0] analog_io;
   input user_clock2;
   output [2:0] user_irq;

   // Internal wires
   wire CTS_4;
   wire CTS_3;
   wire CTS_2;
   wire CTS_1;
   wire gcd_req_rdy;
   wire enq;
   wire gcd_resp_rdy;
   wire deq;
   wire N0;
   wire n1;
   wire n3;
   wire n5;
   wire n7;
   wire n9;
   wire n11;
   wire n13;
   wire n15;
   wire n17;
   wire n19;
   wire n21;
   wire n23;
   wire n25;
   wire n27;
   wire n29;
   wire n31;
   wire n33;
   wire n35;
   wire n37;
   wire n39;
   wire n41;
   wire n43;
   wire n45;
   wire n47;
   wire n49;
   wire n51;
   wire n53;
   wire n55;
   wire n57;
   wire n59;
   wire n61;
   wire n63;
   wire n65;
   wire n67;
   wire n69;
   wire n71;
   wire n73;
   wire n75;
   wire n77;
   wire n79;
   wire n81;
   wire n83;
   wire n85;
   wire n87;
   wire n89;
   wire n91;
   wire n93;
   wire n95;
   wire n97;
   wire n99;
   wire n101;
   wire n103;
   wire n105;
   wire n107;
   wire n109;
   wire n111;
   wire n113;
   wire n115;
   wire n117;
   wire n119;
   wire n121;
   wire n123;
   wire n125;
   wire n127;
   wire n129;
   wire n131;
   wire n133;
   wire n135;
   wire n137;
   wire n139;
   wire n141;
   wire n143;
   wire n145;
   wire n147;
   wire n149;
   wire n151;
   wire n153;
   wire n155;
   wire n157;
   wire n159;
   wire n161;
   wire n163;
   wire n165;
   wire n167;
   wire n169;
   wire n171;
   wire n173;
   wire n175;
   wire n177;
   wire n179;
   wire n181;
   wire n183;
   wire n185;
   wire n187;
   wire n189;
   wire n191;
   wire n193;
   wire n195;
   wire n197;
   wire n199;
   wire n201;
   wire n203;
   wire n205;
   wire n207;
   wire n209;
   wire n211;
   wire n213;
   wire n215;
   wire n217;
   wire n219;
   wire n221;
   wire n223;
   wire n225;
   wire n227;
   wire n229;
   wire n231;
   wire n233;
   wire n235;
   wire n237;
   wire n239;
   wire n241;
   wire n243;
   wire n245;
   wire n247;
   wire n249;
   wire n251;
   wire n253;
   wire n255;
   wire n257;
   wire n259;
   wire n261;
   wire n263;
   wire n265;
   wire n267;
   wire n269;
   wire n271;
   wire n273;
   wire n275;
   wire n277;
   wire n279;
   wire n281;
   wire n283;
   wire n285;
   wire n287;
   wire n289;
   wire n291;
   wire n293;
   wire n295;
   wire n297;
   wire n299;
   wire n301;
   wire n303;
   wire n305;
   wire n307;
   wire n309;
   wire n311;
   wire n313;
   wire n315;
   wire n317;
   wire n319;
   wire n321;
   wire n323;
   wire n325;
   wire n327;
   wire n329;
   wire n331;
   wire n333;
   wire n335;
   wire n337;
   wire n339;
   wire n341;
   wire n343;
   wire n345;
   wire n347;
   wire n349;
   wire n351;
   wire n353;
   wire n355;
   wire n357;
   wire n359;
   wire n361;
   wire n363;
   wire n365;
   wire n367;
   wire n369;
   wire n371;
   wire n373;
   wire n375;
   wire n377;
   wire n379;
   wire n381;
   wire n383;
   wire n385;
   wire n387;
   wire n389;
   wire n391;
   wire n393;
   wire n395;
   wire n397;
   wire n399;
   wire n401;
   wire n403;
   wire n405;
   wire n407;
   wire n409;
   wire n411;
   wire n413;
   wire n415;
   wire n417;
   wire n419;
   wire n421;
   wire n423;
   wire n425;
   wire n427;
   wire n429;
   wire n431;
   wire n433;
   wire n435;
   wire n437;
   wire n439;
   wire n441;
   wire n443;
   wire n445;
   wire n447;
   wire n449;

   sky130_fd_sc_hd__clkinv_2 CTS_ccl_a_inv_00003 (.A(CTS_2),
	.Y(CTS_1));
   sky130_fd_sc_hd__clkinv_2 CTS_ccl_a_inv_00006 (.A(CTS_3),
	.Y(CTS_2));
   sky130_fd_sc_hd__clkinv_8 CTS_ccl_a_inv_00009 (.A(CTS_4),
	.Y(CTS_3));
   sky130_fd_sc_hd__clkinv_4 CTS_ccl_a_inv_00013 (.A(wb_clk_i),
	.Y(CTS_4));
   user_proj_example_GcdUnit_0 GcdUnit_inst (.clk(CTS_1),
	.req_msg(wbs_dat_i),
	.req_rdy(gcd_req_rdy),
	.req_val(enq),
	.reset(wb_rst_i),
	.resp_msg({ wbs_dat_o[15],
		wbs_dat_o[14],
		wbs_dat_o[13],
		wbs_dat_o[12],
		wbs_dat_o[11],
		wbs_dat_o[10],
		wbs_dat_o[9],
		wbs_dat_o[8],
		wbs_dat_o[7],
		wbs_dat_o[6],
		wbs_dat_o[5],
		wbs_dat_o[4],
		wbs_dat_o[3],
		wbs_dat_o[2],
		wbs_dat_o[1],
		wbs_dat_o[0] }),
	.resp_rdy(deq),
	.resp_val(gcd_resp_rdy),
	.clk_clone1(CTS_3));
   sky130_fd_sc_hd__dfxtp_1 ack_reg (.CLK(CTS_1),
	.D(n1),
	.Q(wbs_ack_o));
   sky130_fd_sc_hd__nor2b_1 U3 (.A(wb_rst_i),
	.B_N(N0),
	.Y(n1));
   sky130_fd_sc_hd__and4_1 U9 (.A(wbs_stb_i),
	.B(wbs_cyc_i),
	.C(wbs_we_i),
	.D(gcd_req_rdy),
	.X(enq));
   sky130_fd_sc_hd__nand3_1 U10 (.A(gcd_resp_rdy),
	.B(wbs_stb_i),
	.C(wbs_cyc_i),
	.Y(n3));
   sky130_fd_sc_hd__nor2_1 U11 (.A(wbs_we_i),
	.B(n3),
	.Y(deq));
   sky130_fd_sc_hd__or2_0 U12 (.A(enq),
	.B(deq),
	.X(N0));
   sky130_fd_sc_hd__conb_1 U13 (.HI(n449));
   sky130_fd_sc_hd__conb_1 U14 (.HI(n447));
   sky130_fd_sc_hd__conb_1 U15 (.HI(n445));
   sky130_fd_sc_hd__conb_1 U16 (.HI(n443));
   sky130_fd_sc_hd__conb_1 U17 (.HI(n441));
   sky130_fd_sc_hd__conb_1 U18 (.HI(n439));
   sky130_fd_sc_hd__conb_1 U19 (.HI(n437));
   sky130_fd_sc_hd__conb_1 U20 (.HI(n435));
   sky130_fd_sc_hd__conb_1 U21 (.HI(n433));
   sky130_fd_sc_hd__conb_1 U22 (.HI(n431));
   sky130_fd_sc_hd__conb_1 U23 (.HI(n429));
   sky130_fd_sc_hd__conb_1 U24 (.HI(n427));
   sky130_fd_sc_hd__conb_1 U25 (.HI(n425));
   sky130_fd_sc_hd__conb_1 U26 (.HI(n423));
   sky130_fd_sc_hd__conb_1 U27 (.HI(n421));
   sky130_fd_sc_hd__conb_1 U28 (.HI(n419));
   sky130_fd_sc_hd__conb_1 U29 (.HI(n417));
   sky130_fd_sc_hd__conb_1 U30 (.HI(n415));
   sky130_fd_sc_hd__conb_1 U31 (.HI(n413));
   sky130_fd_sc_hd__conb_1 U32 (.HI(n411));
   sky130_fd_sc_hd__conb_1 U33 (.HI(n409));
   sky130_fd_sc_hd__conb_1 U34 (.HI(n407));
   sky130_fd_sc_hd__conb_1 U35 (.HI(n405));
   sky130_fd_sc_hd__conb_1 U36 (.HI(n403));
   sky130_fd_sc_hd__conb_1 U37 (.HI(n401));
   sky130_fd_sc_hd__conb_1 U38 (.HI(n399));
   sky130_fd_sc_hd__conb_1 U39 (.HI(n397));
   sky130_fd_sc_hd__conb_1 U40 (.HI(n395));
   sky130_fd_sc_hd__conb_1 U41 (.HI(n393));
   sky130_fd_sc_hd__conb_1 U42 (.HI(n391));
   sky130_fd_sc_hd__conb_1 U43 (.HI(n389));
   sky130_fd_sc_hd__conb_1 U44 (.HI(n387));
   sky130_fd_sc_hd__conb_1 U45 (.HI(n385));
   sky130_fd_sc_hd__conb_1 U46 (.HI(n383));
   sky130_fd_sc_hd__conb_1 U47 (.HI(n381));
   sky130_fd_sc_hd__conb_1 U48 (.HI(n379));
   sky130_fd_sc_hd__conb_1 U49 (.HI(n377));
   sky130_fd_sc_hd__conb_1 U50 (.HI(n375));
   sky130_fd_sc_hd__conb_1 U51 (.HI(n373));
   sky130_fd_sc_hd__conb_1 U52 (.HI(n371));
   sky130_fd_sc_hd__conb_1 U53 (.HI(n369));
   sky130_fd_sc_hd__conb_1 U54 (.HI(n367));
   sky130_fd_sc_hd__conb_1 U55 (.HI(n365));
   sky130_fd_sc_hd__conb_1 U56 (.HI(n363));
   sky130_fd_sc_hd__conb_1 U57 (.HI(n361));
   sky130_fd_sc_hd__conb_1 U58 (.HI(n359));
   sky130_fd_sc_hd__conb_1 U59 (.HI(n357));
   sky130_fd_sc_hd__conb_1 U60 (.HI(n355));
   sky130_fd_sc_hd__conb_1 U61 (.HI(n353));
   sky130_fd_sc_hd__conb_1 U62 (.HI(n351));
   sky130_fd_sc_hd__conb_1 U63 (.HI(n349));
   sky130_fd_sc_hd__conb_1 U64 (.HI(n347));
   sky130_fd_sc_hd__conb_1 U65 (.HI(n345));
   sky130_fd_sc_hd__conb_1 U66 (.HI(n343));
   sky130_fd_sc_hd__conb_1 U67 (.HI(n341));
   sky130_fd_sc_hd__conb_1 U68 (.HI(n339));
   sky130_fd_sc_hd__conb_1 U69 (.HI(n337));
   sky130_fd_sc_hd__conb_1 U70 (.HI(n335));
   sky130_fd_sc_hd__conb_1 U71 (.HI(n333));
   sky130_fd_sc_hd__conb_1 U72 (.HI(n331));
   sky130_fd_sc_hd__conb_1 U73 (.HI(n329));
   sky130_fd_sc_hd__conb_1 U74 (.HI(n327));
   sky130_fd_sc_hd__conb_1 U75 (.HI(n325));
   sky130_fd_sc_hd__conb_1 U76 (.HI(n323));
   sky130_fd_sc_hd__conb_1 U77 (.HI(n321));
   sky130_fd_sc_hd__conb_1 U78 (.HI(n319));
   sky130_fd_sc_hd__conb_1 U79 (.HI(n317));
   sky130_fd_sc_hd__conb_1 U80 (.HI(n315));
   sky130_fd_sc_hd__conb_1 U81 (.HI(n313));
   sky130_fd_sc_hd__conb_1 U82 (.HI(n311));
   sky130_fd_sc_hd__conb_1 U83 (.HI(n309));
   sky130_fd_sc_hd__conb_1 U84 (.HI(n307));
   sky130_fd_sc_hd__conb_1 U85 (.HI(n305));
   sky130_fd_sc_hd__conb_1 U86 (.HI(n303));
   sky130_fd_sc_hd__conb_1 U87 (.HI(n301));
   sky130_fd_sc_hd__conb_1 U88 (.HI(n299));
   sky130_fd_sc_hd__conb_1 U89 (.HI(n297));
   sky130_fd_sc_hd__conb_1 U90 (.HI(n295));
   sky130_fd_sc_hd__conb_1 U91 (.HI(n293));
   sky130_fd_sc_hd__conb_1 U92 (.HI(n291));
   sky130_fd_sc_hd__conb_1 U93 (.HI(n289));
   sky130_fd_sc_hd__conb_1 U94 (.HI(n287));
   sky130_fd_sc_hd__conb_1 U95 (.HI(n285));
   sky130_fd_sc_hd__conb_1 U96 (.HI(n283));
   sky130_fd_sc_hd__conb_1 U97 (.HI(n281));
   sky130_fd_sc_hd__conb_1 U98 (.HI(n279));
   sky130_fd_sc_hd__conb_1 U99 (.HI(n277));
   sky130_fd_sc_hd__conb_1 U100 (.HI(n275));
   sky130_fd_sc_hd__conb_1 U101 (.HI(n273));
   sky130_fd_sc_hd__conb_1 U102 (.HI(n271));
   sky130_fd_sc_hd__conb_1 U103 (.HI(n269));
   sky130_fd_sc_hd__conb_1 U104 (.HI(n267));
   sky130_fd_sc_hd__conb_1 U105 (.HI(n265));
   sky130_fd_sc_hd__conb_1 U106 (.HI(n263));
   sky130_fd_sc_hd__conb_1 U107 (.HI(n261));
   sky130_fd_sc_hd__conb_1 U108 (.HI(n259));
   sky130_fd_sc_hd__conb_1 U109 (.HI(n257));
   sky130_fd_sc_hd__conb_1 U110 (.HI(n255));
   sky130_fd_sc_hd__conb_1 U111 (.HI(n253));
   sky130_fd_sc_hd__conb_1 U112 (.HI(n251));
   sky130_fd_sc_hd__conb_1 U113 (.HI(n249));
   sky130_fd_sc_hd__conb_1 U114 (.HI(n247));
   sky130_fd_sc_hd__conb_1 U115 (.HI(n245));
   sky130_fd_sc_hd__conb_1 U116 (.HI(n243));
   sky130_fd_sc_hd__conb_1 U117 (.HI(n241));
   sky130_fd_sc_hd__conb_1 U118 (.HI(n239));
   sky130_fd_sc_hd__conb_1 U119 (.HI(n237));
   sky130_fd_sc_hd__conb_1 U120 (.HI(n235));
   sky130_fd_sc_hd__conb_1 U121 (.HI(n233));
   sky130_fd_sc_hd__conb_1 U122 (.HI(n231));
   sky130_fd_sc_hd__conb_1 U123 (.HI(n229));
   sky130_fd_sc_hd__conb_1 U124 (.HI(n227));
   sky130_fd_sc_hd__conb_1 U125 (.HI(n225));
   sky130_fd_sc_hd__conb_1 U126 (.HI(n223));
   sky130_fd_sc_hd__conb_1 U127 (.HI(n221));
   sky130_fd_sc_hd__conb_1 U128 (.HI(n219));
   sky130_fd_sc_hd__conb_1 U129 (.HI(n217));
   sky130_fd_sc_hd__conb_1 U130 (.HI(n215));
   sky130_fd_sc_hd__conb_1 U131 (.HI(n213));
   sky130_fd_sc_hd__conb_1 U132 (.HI(n211));
   sky130_fd_sc_hd__conb_1 U133 (.HI(n209));
   sky130_fd_sc_hd__conb_1 U134 (.HI(n207));
   sky130_fd_sc_hd__conb_1 U135 (.HI(n205));
   sky130_fd_sc_hd__conb_1 U136 (.HI(n203));
   sky130_fd_sc_hd__conb_1 U137 (.HI(n201));
   sky130_fd_sc_hd__conb_1 U138 (.HI(n199));
   sky130_fd_sc_hd__conb_1 U139 (.HI(n197));
   sky130_fd_sc_hd__conb_1 U140 (.HI(n195));
   sky130_fd_sc_hd__conb_1 U141 (.HI(n193));
   sky130_fd_sc_hd__conb_1 U142 (.HI(n191));
   sky130_fd_sc_hd__conb_1 U143 (.HI(n189));
   sky130_fd_sc_hd__conb_1 U144 (.HI(n187));
   sky130_fd_sc_hd__conb_1 U145 (.HI(n185));
   sky130_fd_sc_hd__conb_1 U146 (.HI(n183));
   sky130_fd_sc_hd__conb_1 U147 (.HI(n181));
   sky130_fd_sc_hd__conb_1 U148 (.HI(n179));
   sky130_fd_sc_hd__conb_1 U149 (.HI(n177));
   sky130_fd_sc_hd__conb_1 U150 (.HI(n175));
   sky130_fd_sc_hd__conb_1 U151 (.HI(n173));
   sky130_fd_sc_hd__conb_1 U152 (.HI(n171));
   sky130_fd_sc_hd__conb_1 U153 (.HI(n169));
   sky130_fd_sc_hd__conb_1 U154 (.HI(n167));
   sky130_fd_sc_hd__conb_1 U155 (.HI(n165));
   sky130_fd_sc_hd__conb_1 U156 (.HI(n163));
   sky130_fd_sc_hd__conb_1 U157 (.HI(n161));
   sky130_fd_sc_hd__conb_1 U158 (.HI(n159));
   sky130_fd_sc_hd__conb_1 U159 (.HI(n157));
   sky130_fd_sc_hd__conb_1 U160 (.HI(n155));
   sky130_fd_sc_hd__conb_1 U161 (.HI(n153));
   sky130_fd_sc_hd__conb_1 U162 (.HI(n151));
   sky130_fd_sc_hd__conb_1 U163 (.HI(n149));
   sky130_fd_sc_hd__conb_1 U164 (.HI(n147));
   sky130_fd_sc_hd__conb_1 U165 (.HI(n145));
   sky130_fd_sc_hd__conb_1 U166 (.HI(n143));
   sky130_fd_sc_hd__conb_1 U167 (.HI(n141));
   sky130_fd_sc_hd__conb_1 U168 (.HI(n139));
   sky130_fd_sc_hd__conb_1 U169 (.HI(n137));
   sky130_fd_sc_hd__conb_1 U170 (.HI(n135));
   sky130_fd_sc_hd__conb_1 U171 (.HI(n133));
   sky130_fd_sc_hd__conb_1 U172 (.HI(n131));
   sky130_fd_sc_hd__conb_1 U173 (.HI(n129));
   sky130_fd_sc_hd__conb_1 U174 (.HI(n127));
   sky130_fd_sc_hd__conb_1 U175 (.HI(n125));
   sky130_fd_sc_hd__conb_1 U176 (.HI(n123));
   sky130_fd_sc_hd__conb_1 U177 (.HI(n121));
   sky130_fd_sc_hd__conb_1 U178 (.HI(n119));
   sky130_fd_sc_hd__conb_1 U179 (.HI(n117));
   sky130_fd_sc_hd__conb_1 U180 (.HI(n115));
   sky130_fd_sc_hd__conb_1 U181 (.HI(n113));
   sky130_fd_sc_hd__conb_1 U182 (.HI(n111));
   sky130_fd_sc_hd__conb_1 U183 (.HI(n109));
   sky130_fd_sc_hd__conb_1 U184 (.HI(n107));
   sky130_fd_sc_hd__conb_1 U185 (.HI(n105));
   sky130_fd_sc_hd__conb_1 U186 (.HI(n103));
   sky130_fd_sc_hd__conb_1 U187 (.HI(n101));
   sky130_fd_sc_hd__conb_1 U188 (.HI(n99));
   sky130_fd_sc_hd__conb_1 U189 (.HI(n97));
   sky130_fd_sc_hd__conb_1 U190 (.HI(n95));
   sky130_fd_sc_hd__conb_1 U191 (.HI(n93));
   sky130_fd_sc_hd__conb_1 U192 (.HI(n91));
   sky130_fd_sc_hd__conb_1 U193 (.HI(n89));
   sky130_fd_sc_hd__conb_1 U194 (.HI(n87));
   sky130_fd_sc_hd__conb_1 U195 (.HI(n85));
   sky130_fd_sc_hd__conb_1 U196 (.HI(n83));
   sky130_fd_sc_hd__conb_1 U197 (.HI(n81));
   sky130_fd_sc_hd__conb_1 U198 (.HI(n79));
   sky130_fd_sc_hd__conb_1 U199 (.HI(n77));
   sky130_fd_sc_hd__conb_1 U200 (.HI(n75));
   sky130_fd_sc_hd__conb_1 U201 (.HI(n73));
   sky130_fd_sc_hd__conb_1 U202 (.HI(n71));
   sky130_fd_sc_hd__conb_1 U203 (.HI(n69));
   sky130_fd_sc_hd__conb_1 U204 (.HI(n67));
   sky130_fd_sc_hd__conb_1 U205 (.HI(n65));
   sky130_fd_sc_hd__conb_1 U206 (.HI(n63));
   sky130_fd_sc_hd__conb_1 U207 (.HI(n61));
   sky130_fd_sc_hd__conb_1 U208 (.HI(n59));
   sky130_fd_sc_hd__conb_1 U209 (.HI(n57));
   sky130_fd_sc_hd__conb_1 U210 (.HI(n55));
   sky130_fd_sc_hd__conb_1 U211 (.HI(n53));
   sky130_fd_sc_hd__conb_1 U212 (.HI(n51));
   sky130_fd_sc_hd__conb_1 U213 (.HI(n49));
   sky130_fd_sc_hd__conb_1 U214 (.HI(n47));
   sky130_fd_sc_hd__conb_1 U215 (.HI(n45));
   sky130_fd_sc_hd__conb_1 U216 (.HI(n43));
   sky130_fd_sc_hd__conb_1 U217 (.HI(n41));
   sky130_fd_sc_hd__conb_1 U218 (.HI(n39));
   sky130_fd_sc_hd__conb_1 U219 (.HI(n37));
   sky130_fd_sc_hd__conb_1 U220 (.HI(n35));
   sky130_fd_sc_hd__conb_1 U221 (.HI(n33));
   sky130_fd_sc_hd__conb_1 U222 (.HI(n31));
   sky130_fd_sc_hd__conb_1 U223 (.HI(n29));
   sky130_fd_sc_hd__conb_1 U224 (.HI(n27));
   sky130_fd_sc_hd__conb_1 U225 (.HI(n25));
   sky130_fd_sc_hd__conb_1 U226 (.HI(n23));
   sky130_fd_sc_hd__conb_1 U227 (.HI(n21));
   sky130_fd_sc_hd__conb_1 U228 (.HI(n19));
   sky130_fd_sc_hd__conb_1 U229 (.HI(n17));
   sky130_fd_sc_hd__conb_1 U230 (.HI(n15));
   sky130_fd_sc_hd__conb_1 U231 (.HI(n13));
   sky130_fd_sc_hd__conb_1 U232 (.HI(n11));
   sky130_fd_sc_hd__conb_1 U233 (.HI(n9));
   sky130_fd_sc_hd__conb_1 U234 (.HI(n7));
   sky130_fd_sc_hd__conb_1 U235 (.HI(n5));
   sky130_fd_sc_hd__clkinv_1 U236 (.A(n5),
	.Y(user_irq[0]));
   sky130_fd_sc_hd__clkinv_1 U237 (.A(n7),
	.Y(user_irq[1]));
   sky130_fd_sc_hd__clkinv_1 U238 (.A(n9),
	.Y(user_irq[2]));
   sky130_fd_sc_hd__clkinv_1 U239 (.A(n11),
	.Y(io_oeb[0]));
   sky130_fd_sc_hd__clkinv_1 U240 (.A(n13),
	.Y(io_oeb[1]));
   sky130_fd_sc_hd__clkinv_1 U241 (.A(n15),
	.Y(io_oeb[2]));
   sky130_fd_sc_hd__clkinv_1 U242 (.A(n17),
	.Y(io_oeb[3]));
   sky130_fd_sc_hd__clkinv_1 U243 (.A(n19),
	.Y(io_oeb[4]));
   sky130_fd_sc_hd__clkinv_1 U244 (.A(n21),
	.Y(io_oeb[5]));
   sky130_fd_sc_hd__clkinv_1 U245 (.A(n23),
	.Y(io_oeb[6]));
   sky130_fd_sc_hd__clkinv_1 U246 (.A(n25),
	.Y(io_oeb[7]));
   sky130_fd_sc_hd__clkinv_1 U247 (.A(n27),
	.Y(io_oeb[8]));
   sky130_fd_sc_hd__clkinv_1 U248 (.A(n29),
	.Y(io_oeb[9]));
   sky130_fd_sc_hd__clkinv_1 U249 (.A(n31),
	.Y(io_oeb[10]));
   sky130_fd_sc_hd__clkinv_1 U250 (.A(n33),
	.Y(io_oeb[11]));
   sky130_fd_sc_hd__clkinv_1 U251 (.A(n35),
	.Y(io_oeb[12]));
   sky130_fd_sc_hd__clkinv_1 U252 (.A(n37),
	.Y(io_oeb[13]));
   sky130_fd_sc_hd__clkinv_1 U253 (.A(n39),
	.Y(io_oeb[14]));
   sky130_fd_sc_hd__clkinv_1 U254 (.A(n41),
	.Y(io_oeb[15]));
   sky130_fd_sc_hd__clkinv_1 U255 (.A(n43),
	.Y(io_oeb[16]));
   sky130_fd_sc_hd__clkinv_1 U256 (.A(n45),
	.Y(io_oeb[17]));
   sky130_fd_sc_hd__clkinv_1 U257 (.A(n47),
	.Y(io_oeb[18]));
   sky130_fd_sc_hd__clkinv_1 U258 (.A(n49),
	.Y(io_oeb[19]));
   sky130_fd_sc_hd__clkinv_1 U259 (.A(n51),
	.Y(io_oeb[20]));
   sky130_fd_sc_hd__clkinv_1 U260 (.A(n53),
	.Y(io_oeb[21]));
   sky130_fd_sc_hd__clkinv_1 U261 (.A(n55),
	.Y(io_oeb[22]));
   sky130_fd_sc_hd__clkinv_1 U262 (.A(n57),
	.Y(io_oeb[23]));
   sky130_fd_sc_hd__clkinv_1 U263 (.A(n59),
	.Y(io_oeb[24]));
   sky130_fd_sc_hd__clkinv_1 U264 (.A(n61),
	.Y(io_oeb[25]));
   sky130_fd_sc_hd__clkinv_1 U265 (.A(n63),
	.Y(io_oeb[26]));
   sky130_fd_sc_hd__clkinv_1 U266 (.A(n65),
	.Y(io_oeb[27]));
   sky130_fd_sc_hd__clkinv_1 U267 (.A(n67),
	.Y(io_oeb[28]));
   sky130_fd_sc_hd__clkinv_1 U268 (.A(n69),
	.Y(io_oeb[29]));
   sky130_fd_sc_hd__clkinv_1 U269 (.A(n71),
	.Y(io_oeb[30]));
   sky130_fd_sc_hd__clkinv_1 U270 (.A(n73),
	.Y(io_oeb[31]));
   sky130_fd_sc_hd__clkinv_1 U271 (.A(n75),
	.Y(io_oeb[32]));
   sky130_fd_sc_hd__clkinv_1 U272 (.A(n77),
	.Y(io_oeb[33]));
   sky130_fd_sc_hd__clkinv_1 U273 (.A(n79),
	.Y(io_oeb[34]));
   sky130_fd_sc_hd__clkinv_1 U274 (.A(n81),
	.Y(io_oeb[35]));
   sky130_fd_sc_hd__clkinv_1 U275 (.A(n83),
	.Y(io_oeb[36]));
   sky130_fd_sc_hd__clkinv_1 U276 (.A(n85),
	.Y(io_oeb[37]));
   sky130_fd_sc_hd__clkinv_1 U277 (.A(n87),
	.Y(io_out[0]));
   sky130_fd_sc_hd__clkinv_1 U278 (.A(n89),
	.Y(io_out[1]));
   sky130_fd_sc_hd__clkinv_1 U279 (.A(n91),
	.Y(io_out[2]));
   sky130_fd_sc_hd__clkinv_1 U280 (.A(n93),
	.Y(io_out[3]));
   sky130_fd_sc_hd__clkinv_1 U281 (.A(n95),
	.Y(io_out[4]));
   sky130_fd_sc_hd__clkinv_1 U282 (.A(n97),
	.Y(io_out[5]));
   sky130_fd_sc_hd__clkinv_1 U283 (.A(n99),
	.Y(io_out[6]));
   sky130_fd_sc_hd__clkinv_1 U284 (.A(n101),
	.Y(io_out[7]));
   sky130_fd_sc_hd__clkinv_1 U285 (.A(n103),
	.Y(io_out[8]));
   sky130_fd_sc_hd__clkinv_1 U286 (.A(n105),
	.Y(io_out[9]));
   sky130_fd_sc_hd__clkinv_1 U287 (.A(n107),
	.Y(io_out[10]));
   sky130_fd_sc_hd__clkinv_1 U288 (.A(n109),
	.Y(io_out[11]));
   sky130_fd_sc_hd__clkinv_1 U289 (.A(n111),
	.Y(io_out[12]));
   sky130_fd_sc_hd__clkinv_1 U290 (.A(n113),
	.Y(io_out[13]));
   sky130_fd_sc_hd__clkinv_1 U291 (.A(n115),
	.Y(io_out[14]));
   sky130_fd_sc_hd__clkinv_1 U292 (.A(n117),
	.Y(io_out[15]));
   sky130_fd_sc_hd__clkinv_1 U293 (.A(n119),
	.Y(io_out[16]));
   sky130_fd_sc_hd__clkinv_1 U294 (.A(n121),
	.Y(io_out[17]));
   sky130_fd_sc_hd__clkinv_1 U295 (.A(n123),
	.Y(io_out[18]));
   sky130_fd_sc_hd__clkinv_1 U296 (.A(n125),
	.Y(io_out[19]));
   sky130_fd_sc_hd__clkinv_1 U297 (.A(n127),
	.Y(io_out[20]));
   sky130_fd_sc_hd__clkinv_1 U298 (.A(n129),
	.Y(io_out[21]));
   sky130_fd_sc_hd__clkinv_1 U299 (.A(n131),
	.Y(io_out[22]));
   sky130_fd_sc_hd__clkinv_1 U300 (.A(n133),
	.Y(io_out[23]));
   sky130_fd_sc_hd__clkinv_1 U301 (.A(n135),
	.Y(io_out[24]));
   sky130_fd_sc_hd__clkinv_1 U302 (.A(n137),
	.Y(io_out[25]));
   sky130_fd_sc_hd__clkinv_1 U303 (.A(n139),
	.Y(io_out[26]));
   sky130_fd_sc_hd__clkinv_1 U304 (.A(n141),
	.Y(io_out[27]));
   sky130_fd_sc_hd__clkinv_1 U305 (.A(n143),
	.Y(io_out[28]));
   sky130_fd_sc_hd__clkinv_1 U306 (.A(n145),
	.Y(io_out[29]));
   sky130_fd_sc_hd__clkinv_1 U307 (.A(n147),
	.Y(io_out[30]));
   sky130_fd_sc_hd__clkinv_1 U308 (.A(n149),
	.Y(io_out[31]));
   sky130_fd_sc_hd__clkinv_1 U309 (.A(n151),
	.Y(io_out[32]));
   sky130_fd_sc_hd__clkinv_1 U310 (.A(n153),
	.Y(io_out[33]));
   sky130_fd_sc_hd__clkinv_1 U311 (.A(n155),
	.Y(io_out[34]));
   sky130_fd_sc_hd__clkinv_1 U312 (.A(n157),
	.Y(io_out[35]));
   sky130_fd_sc_hd__clkinv_1 U313 (.A(n159),
	.Y(io_out[36]));
   sky130_fd_sc_hd__clkinv_1 U314 (.A(n161),
	.Y(io_out[37]));
   sky130_fd_sc_hd__clkinv_1 U315 (.A(n163),
	.Y(la_data_out[0]));
   sky130_fd_sc_hd__clkinv_1 U316 (.A(n165),
	.Y(la_data_out[1]));
   sky130_fd_sc_hd__clkinv_1 U317 (.A(n167),
	.Y(la_data_out[2]));
   sky130_fd_sc_hd__clkinv_1 U318 (.A(n169),
	.Y(la_data_out[3]));
   sky130_fd_sc_hd__clkinv_1 U319 (.A(n171),
	.Y(la_data_out[4]));
   sky130_fd_sc_hd__clkinv_1 U320 (.A(n173),
	.Y(la_data_out[5]));
   sky130_fd_sc_hd__clkinv_1 U321 (.A(n175),
	.Y(la_data_out[6]));
   sky130_fd_sc_hd__clkinv_1 U322 (.A(n177),
	.Y(la_data_out[7]));
   sky130_fd_sc_hd__clkinv_1 U323 (.A(n179),
	.Y(la_data_out[8]));
   sky130_fd_sc_hd__clkinv_1 U324 (.A(n181),
	.Y(la_data_out[9]));
   sky130_fd_sc_hd__clkinv_1 U325 (.A(n183),
	.Y(la_data_out[10]));
   sky130_fd_sc_hd__clkinv_1 U326 (.A(n185),
	.Y(la_data_out[11]));
   sky130_fd_sc_hd__clkinv_1 U327 (.A(n187),
	.Y(la_data_out[12]));
   sky130_fd_sc_hd__clkinv_1 U328 (.A(n189),
	.Y(la_data_out[13]));
   sky130_fd_sc_hd__clkinv_1 U329 (.A(n191),
	.Y(la_data_out[14]));
   sky130_fd_sc_hd__clkinv_1 U330 (.A(n193),
	.Y(la_data_out[15]));
   sky130_fd_sc_hd__clkinv_1 U331 (.A(n195),
	.Y(la_data_out[16]));
   sky130_fd_sc_hd__clkinv_1 U332 (.A(n197),
	.Y(la_data_out[17]));
   sky130_fd_sc_hd__clkinv_1 U333 (.A(n199),
	.Y(la_data_out[18]));
   sky130_fd_sc_hd__clkinv_1 U334 (.A(n201),
	.Y(la_data_out[19]));
   sky130_fd_sc_hd__clkinv_1 U335 (.A(n203),
	.Y(la_data_out[20]));
   sky130_fd_sc_hd__clkinv_1 U336 (.A(n205),
	.Y(la_data_out[21]));
   sky130_fd_sc_hd__clkinv_1 U337 (.A(n207),
	.Y(la_data_out[22]));
   sky130_fd_sc_hd__clkinv_1 U338 (.A(n209),
	.Y(la_data_out[23]));
   sky130_fd_sc_hd__clkinv_1 U339 (.A(n211),
	.Y(la_data_out[24]));
   sky130_fd_sc_hd__clkinv_1 U340 (.A(n213),
	.Y(la_data_out[25]));
   sky130_fd_sc_hd__clkinv_1 U341 (.A(n215),
	.Y(la_data_out[26]));
   sky130_fd_sc_hd__clkinv_1 U342 (.A(n217),
	.Y(la_data_out[27]));
   sky130_fd_sc_hd__clkinv_1 U343 (.A(n219),
	.Y(la_data_out[28]));
   sky130_fd_sc_hd__clkinv_1 U344 (.A(n221),
	.Y(la_data_out[29]));
   sky130_fd_sc_hd__clkinv_1 U345 (.A(n223),
	.Y(la_data_out[30]));
   sky130_fd_sc_hd__clkinv_1 U346 (.A(n225),
	.Y(la_data_out[31]));
   sky130_fd_sc_hd__clkinv_1 U347 (.A(n227),
	.Y(la_data_out[32]));
   sky130_fd_sc_hd__clkinv_1 U348 (.A(n229),
	.Y(la_data_out[33]));
   sky130_fd_sc_hd__clkinv_1 U349 (.A(n231),
	.Y(la_data_out[34]));
   sky130_fd_sc_hd__clkinv_1 U350 (.A(n233),
	.Y(la_data_out[35]));
   sky130_fd_sc_hd__clkinv_1 U351 (.A(n235),
	.Y(la_data_out[36]));
   sky130_fd_sc_hd__clkinv_1 U352 (.A(n237),
	.Y(la_data_out[37]));
   sky130_fd_sc_hd__clkinv_1 U353 (.A(n239),
	.Y(la_data_out[38]));
   sky130_fd_sc_hd__clkinv_1 U354 (.A(n241),
	.Y(la_data_out[39]));
   sky130_fd_sc_hd__clkinv_1 U355 (.A(n243),
	.Y(la_data_out[40]));
   sky130_fd_sc_hd__clkinv_1 U356 (.A(n245),
	.Y(la_data_out[41]));
   sky130_fd_sc_hd__clkinv_1 U357 (.A(n247),
	.Y(la_data_out[42]));
   sky130_fd_sc_hd__clkinv_1 U358 (.A(n249),
	.Y(la_data_out[43]));
   sky130_fd_sc_hd__clkinv_1 U359 (.A(n251),
	.Y(la_data_out[44]));
   sky130_fd_sc_hd__clkinv_1 U360 (.A(n253),
	.Y(la_data_out[45]));
   sky130_fd_sc_hd__clkinv_1 U361 (.A(n255),
	.Y(la_data_out[46]));
   sky130_fd_sc_hd__clkinv_1 U362 (.A(n257),
	.Y(la_data_out[47]));
   sky130_fd_sc_hd__clkinv_1 U363 (.A(n259),
	.Y(la_data_out[48]));
   sky130_fd_sc_hd__clkinv_1 U364 (.A(n261),
	.Y(la_data_out[49]));
   sky130_fd_sc_hd__clkinv_1 U365 (.A(n263),
	.Y(la_data_out[50]));
   sky130_fd_sc_hd__clkinv_1 U366 (.A(n265),
	.Y(la_data_out[51]));
   sky130_fd_sc_hd__clkinv_1 U367 (.A(n267),
	.Y(la_data_out[52]));
   sky130_fd_sc_hd__clkinv_1 U368 (.A(n269),
	.Y(la_data_out[53]));
   sky130_fd_sc_hd__clkinv_1 U369 (.A(n271),
	.Y(la_data_out[54]));
   sky130_fd_sc_hd__clkinv_1 U370 (.A(n273),
	.Y(la_data_out[55]));
   sky130_fd_sc_hd__clkinv_1 U371 (.A(n275),
	.Y(la_data_out[56]));
   sky130_fd_sc_hd__clkinv_1 U372 (.A(n277),
	.Y(la_data_out[57]));
   sky130_fd_sc_hd__clkinv_1 U373 (.A(n279),
	.Y(la_data_out[58]));
   sky130_fd_sc_hd__clkinv_1 U374 (.A(n281),
	.Y(la_data_out[59]));
   sky130_fd_sc_hd__clkinv_1 U375 (.A(n283),
	.Y(la_data_out[60]));
   sky130_fd_sc_hd__clkinv_1 U376 (.A(n285),
	.Y(la_data_out[61]));
   sky130_fd_sc_hd__clkinv_1 U377 (.A(n287),
	.Y(la_data_out[62]));
   sky130_fd_sc_hd__clkinv_1 U378 (.A(n289),
	.Y(la_data_out[63]));
   sky130_fd_sc_hd__clkinv_1 U379 (.A(n291),
	.Y(la_data_out[64]));
   sky130_fd_sc_hd__clkinv_1 U380 (.A(n293),
	.Y(la_data_out[65]));
   sky130_fd_sc_hd__clkinv_1 U381 (.A(n295),
	.Y(la_data_out[66]));
   sky130_fd_sc_hd__clkinv_1 U382 (.A(n297),
	.Y(la_data_out[67]));
   sky130_fd_sc_hd__clkinv_1 U383 (.A(n299),
	.Y(la_data_out[68]));
   sky130_fd_sc_hd__clkinv_1 U384 (.A(n301),
	.Y(la_data_out[69]));
   sky130_fd_sc_hd__clkinv_1 U385 (.A(n303),
	.Y(la_data_out[70]));
   sky130_fd_sc_hd__clkinv_1 U386 (.A(n305),
	.Y(la_data_out[71]));
   sky130_fd_sc_hd__clkinv_1 U387 (.A(n307),
	.Y(la_data_out[72]));
   sky130_fd_sc_hd__clkinv_1 U388 (.A(n309),
	.Y(la_data_out[73]));
   sky130_fd_sc_hd__clkinv_1 U389 (.A(n311),
	.Y(la_data_out[74]));
   sky130_fd_sc_hd__clkinv_1 U390 (.A(n313),
	.Y(la_data_out[75]));
   sky130_fd_sc_hd__clkinv_1 U391 (.A(n315),
	.Y(la_data_out[76]));
   sky130_fd_sc_hd__clkinv_1 U392 (.A(n317),
	.Y(la_data_out[77]));
   sky130_fd_sc_hd__clkinv_1 U393 (.A(n319),
	.Y(la_data_out[78]));
   sky130_fd_sc_hd__clkinv_1 U394 (.A(n321),
	.Y(la_data_out[79]));
   sky130_fd_sc_hd__clkinv_1 U395 (.A(n323),
	.Y(la_data_out[80]));
   sky130_fd_sc_hd__clkinv_1 U396 (.A(n325),
	.Y(la_data_out[81]));
   sky130_fd_sc_hd__clkinv_1 U397 (.A(n327),
	.Y(la_data_out[82]));
   sky130_fd_sc_hd__clkinv_1 U398 (.A(n329),
	.Y(la_data_out[83]));
   sky130_fd_sc_hd__clkinv_1 U399 (.A(n331),
	.Y(la_data_out[84]));
   sky130_fd_sc_hd__clkinv_1 U400 (.A(n333),
	.Y(la_data_out[85]));
   sky130_fd_sc_hd__clkinv_1 U401 (.A(n335),
	.Y(la_data_out[86]));
   sky130_fd_sc_hd__clkinv_1 U402 (.A(n337),
	.Y(la_data_out[87]));
   sky130_fd_sc_hd__clkinv_1 U403 (.A(n339),
	.Y(la_data_out[88]));
   sky130_fd_sc_hd__clkinv_1 U404 (.A(n341),
	.Y(la_data_out[89]));
   sky130_fd_sc_hd__clkinv_1 U405 (.A(n343),
	.Y(la_data_out[90]));
   sky130_fd_sc_hd__clkinv_1 U406 (.A(n345),
	.Y(la_data_out[91]));
   sky130_fd_sc_hd__clkinv_1 U407 (.A(n347),
	.Y(la_data_out[92]));
   sky130_fd_sc_hd__clkinv_1 U408 (.A(n349),
	.Y(la_data_out[93]));
   sky130_fd_sc_hd__clkinv_1 U409 (.A(n351),
	.Y(la_data_out[94]));
   sky130_fd_sc_hd__clkinv_1 U410 (.A(n353),
	.Y(la_data_out[95]));
   sky130_fd_sc_hd__clkinv_1 U411 (.A(n355),
	.Y(la_data_out[96]));
   sky130_fd_sc_hd__clkinv_1 U412 (.A(n357),
	.Y(la_data_out[97]));
   sky130_fd_sc_hd__clkinv_1 U413 (.A(n359),
	.Y(la_data_out[98]));
   sky130_fd_sc_hd__clkinv_1 U414 (.A(n361),
	.Y(la_data_out[99]));
   sky130_fd_sc_hd__clkinv_1 U415 (.A(n363),
	.Y(la_data_out[100]));
   sky130_fd_sc_hd__clkinv_1 U416 (.A(n365),
	.Y(la_data_out[101]));
   sky130_fd_sc_hd__clkinv_1 U417 (.A(n367),
	.Y(la_data_out[102]));
   sky130_fd_sc_hd__clkinv_1 U418 (.A(n369),
	.Y(la_data_out[103]));
   sky130_fd_sc_hd__clkinv_1 U419 (.A(n371),
	.Y(la_data_out[104]));
   sky130_fd_sc_hd__clkinv_1 U420 (.A(n373),
	.Y(la_data_out[105]));
   sky130_fd_sc_hd__clkinv_1 U421 (.A(n375),
	.Y(la_data_out[106]));
   sky130_fd_sc_hd__clkinv_1 U422 (.A(n377),
	.Y(la_data_out[107]));
   sky130_fd_sc_hd__clkinv_1 U423 (.A(n379),
	.Y(la_data_out[108]));
   sky130_fd_sc_hd__clkinv_1 U424 (.A(n381),
	.Y(la_data_out[109]));
   sky130_fd_sc_hd__clkinv_1 U425 (.A(n383),
	.Y(la_data_out[110]));
   sky130_fd_sc_hd__clkinv_1 U426 (.A(n385),
	.Y(la_data_out[111]));
   sky130_fd_sc_hd__clkinv_1 U427 (.A(n387),
	.Y(la_data_out[112]));
   sky130_fd_sc_hd__clkinv_1 U428 (.A(n389),
	.Y(la_data_out[113]));
   sky130_fd_sc_hd__clkinv_1 U429 (.A(n391),
	.Y(la_data_out[114]));
   sky130_fd_sc_hd__clkinv_1 U430 (.A(n393),
	.Y(la_data_out[115]));
   sky130_fd_sc_hd__clkinv_1 U431 (.A(n395),
	.Y(la_data_out[116]));
   sky130_fd_sc_hd__clkinv_1 U432 (.A(n397),
	.Y(la_data_out[117]));
   sky130_fd_sc_hd__clkinv_1 U433 (.A(n399),
	.Y(la_data_out[118]));
   sky130_fd_sc_hd__clkinv_1 U434 (.A(n401),
	.Y(la_data_out[119]));
   sky130_fd_sc_hd__clkinv_1 U435 (.A(n403),
	.Y(la_data_out[120]));
   sky130_fd_sc_hd__clkinv_1 U436 (.A(n405),
	.Y(la_data_out[121]));
   sky130_fd_sc_hd__clkinv_1 U437 (.A(n407),
	.Y(la_data_out[122]));
   sky130_fd_sc_hd__clkinv_1 U438 (.A(n409),
	.Y(la_data_out[123]));
   sky130_fd_sc_hd__clkinv_1 U439 (.A(n411),
	.Y(la_data_out[124]));
   sky130_fd_sc_hd__clkinv_1 U440 (.A(n413),
	.Y(la_data_out[125]));
   sky130_fd_sc_hd__clkinv_1 U441 (.A(n415),
	.Y(la_data_out[126]));
   sky130_fd_sc_hd__clkinv_1 U442 (.A(n417),
	.Y(la_data_out[127]));
   sky130_fd_sc_hd__clkinv_1 U443 (.A(n419),
	.Y(wbs_dat_o[16]));
   sky130_fd_sc_hd__clkinv_1 U444 (.A(n421),
	.Y(wbs_dat_o[17]));
   sky130_fd_sc_hd__clkinv_1 U445 (.A(n423),
	.Y(wbs_dat_o[18]));
   sky130_fd_sc_hd__clkinv_1 U446 (.A(n425),
	.Y(wbs_dat_o[19]));
   sky130_fd_sc_hd__clkinv_1 U447 (.A(n427),
	.Y(wbs_dat_o[20]));
   sky130_fd_sc_hd__clkinv_1 U448 (.A(n429),
	.Y(wbs_dat_o[21]));
   sky130_fd_sc_hd__clkinv_1 U449 (.A(n431),
	.Y(wbs_dat_o[22]));
   sky130_fd_sc_hd__clkinv_1 U450 (.A(n433),
	.Y(wbs_dat_o[23]));
   sky130_fd_sc_hd__clkinv_1 U451 (.A(n435),
	.Y(wbs_dat_o[24]));
   sky130_fd_sc_hd__clkinv_1 U452 (.A(n437),
	.Y(wbs_dat_o[25]));
   sky130_fd_sc_hd__clkinv_1 U453 (.A(n439),
	.Y(wbs_dat_o[26]));
   sky130_fd_sc_hd__clkinv_1 U454 (.A(n441),
	.Y(wbs_dat_o[27]));
   sky130_fd_sc_hd__clkinv_1 U455 (.A(n443),
	.Y(wbs_dat_o[28]));
   sky130_fd_sc_hd__clkinv_1 U456 (.A(n445),
	.Y(wbs_dat_o[29]));
   sky130_fd_sc_hd__clkinv_1 U457 (.A(n447),
	.Y(wbs_dat_o[30]));
   sky130_fd_sc_hd__clkinv_1 U458 (.A(n449),
	.Y(wbs_dat_o[31]));
endmodule

